# Generated by Django 6.0.3 on 2026-03-17 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VegetationSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surveyed_at', models.DateField()),
                ('species_name', models.CharField(max_length=200)),
                ('common_name', models.CharField(blank=True, max_length=200)),
                ('cover_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('invasive', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vegetation_surveys', to='sites.monitoringsite')),
            ],
            options={
                'ordering': ['-surveyed_at'],
            },
        ),
    ]
