# Generated by Django 6.0.3 on 2026-04-14 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlife', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wildlifesighting',
            name='inaturalist_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='wildlifesighting',
            name='inaturalist_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='wildlifesighting',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual entry'), ('inaturalist', 'iNaturalist')], default='manual', max_length=20),
        ),
    ]
