# Generated by Django 6.0.3 on 2026-04-21 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlife', '0002_wildlifesighting_inaturalist_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wildlifesighting',
            name='taxon_type',
            field=models.CharField(choices=[('animalia', 'Animal'), ('plantae', 'Plant'), ('fungi', 'Fungi'), ('other', 'Other'), ('unknown', 'Unknown')], default='unknown', max_length=20),
        ),
    ]
