# Generated by Django 6.0.3 on 2026-04-13 10:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SitePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='site_photos/%Y/%m/')),
                ('category', models.CharField(choices=[('water_quality', 'Water Quality'), ('vegetation', 'Vegetation'), ('wildlife', 'Wildlife'), ('planting', 'Planting Event'), ('general', 'General Site')], default='general', max_length=20)),
                ('caption', models.CharField(blank=True, max_length=300)),
                ('recorded_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='photos', to='sites.monitoringsite')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_photos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
    ]
