# Generated by Django 6.0.3 on 2026-04-13 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planting_date', models.DateField()),
                ('species_name', models.CharField(max_length=200)),
                ('common_name', models.CharField(blank=True, max_length=200)),
                ('quantity_planted', models.PositiveIntegerField()),
                ('planting_method', models.CharField(blank=True, help_text='e.g. seedling, direct seed, cutting', max_length=100)),
                ('planted_by', models.CharField(blank=True, help_text='Organisation or team responsible', max_length=200)),
                ('funding_source', models.CharField(blank=True, help_text='e.g. Reforest Action, DEA&DP, LandCare', max_length=200)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('completed', 'Completed'), ('failed', 'Failed')], default='completed', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planting_events', to='sites.monitoringsite')),
            ],
            options={
                'ordering': ['-planting_date'],
            },
        ),
        migrations.CreateModel(
            name='SurvivalCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_date', models.DateField()),
                ('check_type', models.CharField(choices=[('3_month', '3 Month Check'), ('6_month', '6 Month Check'), ('12_month', '12 Month Check'), ('24_month', '24 Month Check'), ('adhoc', 'Ad Hoc Check')], max_length=20)),
                ('plants_surviving', models.PositiveIntegerField()),
                ('survival_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Auto-calculated as percentage', max_digits=5, null=True)),
                ('notes', models.TextField(blank=True)),
                ('checked_by', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('planting_event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='survival_checks', to='planting.plantingevent')),
            ],
            options={
                'ordering': ['-check_date'],
            },
        ),
    ]
