# Generated by Django 6.0.3 on 2026-04-20 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='plan',
            field=models.CharField(choices=[('starter', 'Starter — R1,500/month'), ('professional', 'Professional — R4,500/month'), ('programme', 'Programme — R10,000/month')], default='starter', max_length=20),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='is_superorg',
            field=models.BooleanField(default=False),
        ),
    ]
