# Generated by Django 6.0.3 on 2026-04-14 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0001_initial'),
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoringsite',
            name='organisation',
            field=models.ForeignKey(blank=True, help_text='Which organisation manages this site', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sites', to='organisations.organisation'),
        ),
    ]
